title: The Fuzzing Book
author: Andreas Zeller, Rahul Gopinath, Marcel Böhme, Gordon Fraser, and Christian Holler
copyright: 2021-2025 CISPA Helmholtz Center for Information Security (www.cispa.de); © 2018-2020 Saarland University. © 2018-2025 external contributors. All Rights Reserved
logo: "_static/fuzzingbook.png"

bibtex_bibfiles:
  - fuzzingbook.bib

latex:
  latex_documents:
     targetname: fuzzingbook.tex

sphinx:
  config:
    latex_engine: xelatex
    latex_show_pagerefs: true
    latex_show_urls: footnote

execute:
  execute_notebooks: 'off'
  stderr_output: show
  timeout: 300

parse:
  myst_enable_extensions:
    # - amsmath
    - colon_fence
    - dollarmath
    # - html_admonition
    # - html_image
    - linkify
    - replacements
    - smartquotes
    - strikethrough
    - substitution
    - tasklist
    - deflist

html:
  announcement: '<p>This is a beta version of fuzzingbook.org, currently in development. See the <a href="https://fuzzingbook.org/classic/"  style="color:white!important;">classic site</a> for resources.</p>'
  use_issues_button: true
  use_repository_button: true
  extra_footer: |
    <div>
      Copyright &copy; 
      2021–2025 <a href="https://www.cispa.de/">CISPA Helmholtz Center for Information Security</a>. Copyright &copy; 2018-2020 <a href="https://www.uni-saarland.de/">Saarland University</a>. Copyright &copy; 2018-2025 external contributors.
      The content of this project is licensed under the <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>. The source code that is part of the content, as well as the source code used to format and display that content is licensed under the <a href="https://github.com/uds-se/fuzzingbook/blob/master/LICENSE.md#mit-license">MIT License</a>. <a href="https://cispa.de/en/impressum">Imprint</a>.
    </div>
    
sphinx:
  config:
    html_show_copyright: false

repository:
  url: "https://github.com/uds-se/fuzzingbook/"
  path_to_book: "docs/notebooks"
  branch: master

launch_buttons:
  binderhub_url: "https://mybinder.org"
  thebe: false  # Does not support local imports
